//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _52_ControlUsuarios
{
    using _52_ControlUsuariosDataAccess;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaIntegralReportesEntities : DbContext
    {
        public SistemaIntegralReportesEntities()
            : base("name=SistemaIntegralReportesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<conf_accesos> conf_accesos { get; set; }
        public virtual DbSet<conf_modulo> conf_modulo { get; set; }
        public virtual DbSet<conf_perfiles> conf_perfiles { get; set; }
        public virtual DbSet<conf_usuarios> conf_usuarios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
