// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaIntegralReportes.AplicacionDePedidos;

#nullable disable

namespace SistemaIntegralReportes.AplicacionDePedidos.Migrations
{
    [DbContext(typeof(ApplicationDbContextCompras))]
    partial class ApplicationDbContextComprasModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Almacen", b =>
                {
                    b.Property<int>("IdAlmacen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlmacen"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdAlmacen");

                    b.ToTable("comp_almacen");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.AreaDestino", b =>
                {
                    b.Property<int>("IdAreaDestino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAreaDestino"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdAreaDestino");

                    b.ToTable("comp_area_destino");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.CentroDeCosto", b =>
                {
                    b.Property<int>("IdCentroDeCosto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCentroDeCosto"), 1L, 1);

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("CodigoAlternativo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("IdCentroDeCosto");

                    b.ToTable("comp_centro_de_costo");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("IdDepartamento");

                    b.ToTable("comp_departamento");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("comp_empresa");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.EstadoDeSolicitud", b =>
                {
                    b.Property<int>("IdEstadoDeSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoDeSolicitud"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstadoDeSolicitud");

                    b.ToTable("comp_estado_de_solicitud");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.LineaDeSolicitud", b =>
                {
                    b.Property<int>("IdLineaDeSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLineaDeSolicitud"), 1L, 1);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdAreaDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdOrdenDeSolicitud")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdLineaDeSolicitud");

                    b.HasIndex("IdAreaDestino");

                    b.HasIndex("IdOrdenDeSolicitud");

                    b.HasIndex("IdProducto");

                    b.ToTable("comp_linea_de_solicitud");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.OrdenDeSolicitud", b =>
                {
                    b.Property<int>("IdOrdenDeSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdenDeSolicitud"), 1L, 1);

                    b.Property<DateTime>("FechaDecreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCentroDeCosto")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoDeSolicitud")
                        .HasColumnType("int");

                    b.Property<int>("IdPriodidadDeOrden")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioSolicitante")
                        .HasColumnType("int");

                    b.HasKey("IdOrdenDeSolicitud");

                    b.HasIndex("IdCentroDeCosto");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEstadoDeSolicitud");

                    b.HasIndex("IdPriodidadDeOrden");

                    b.HasIndex("IdUsuarioSolicitante");

                    b.ToTable("comp_orden_de_solicitud");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.PrioridadDeOrden", b =>
                {
                    b.Property<int>("IdPriodidadDeOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPriodidadDeOrden"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("IdPriodidadDeOrden");

                    b.ToTable("comp_prioridad_de_orden");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"), 1L, 1);

                    b.Property<string>("CodigoDeProducto")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CodigoDeProductoAlternativo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CodigoDeProductoAlternativo2")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaDeActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoDeUnidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdTipoDeUnidad");

                    b.ToTable("comp_producto");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.RolDeUsuario", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("IdRol");

                    b.ToTable("comp_rol_de_usuario");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.StockProducto", b =>
                {
                    b.Property<int>("IdStockProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStockProducto"), 1L, 1);

                    b.Property<DateTime>("FechaDeActualizacion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdStockProducto");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdProducto");

                    b.ToTable("comp_stock_producto");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.TipoDeUnidad", b =>
                {
                    b.Property<int>("IdTipoDeUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDeUnidad"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdTipoDeUnidad");

                    b.ToTable("comp_tipo_de_unidad");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.UbicacionDestino", b =>
                {
                    b.Property<int>("IdUbicacionDestino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUbicacionDestino"), 1L, 1);

                    b.Property<int>("AlmacenIdAlmacen")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdUbicacionDestino");

                    b.HasIndex("AlmacenIdAlmacen");

                    b.ToTable("comp_ubicacion_destino");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.UsuarioSolicitante", b =>
                {
                    b.Property<int>("IdUsuarioSolicitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioSolicitante"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("IdUsuarioSolicitante");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdRol");

                    b.ToTable("comp_usuario_solicitante");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.LineaDeSolicitud", b =>
                {
                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.AreaDestino", "AreaDestino")
                        .WithMany()
                        .HasForeignKey("IdAreaDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.OrdenDeSolicitud", "OrdenDeSolicitud")
                        .WithMany()
                        .HasForeignKey("IdOrdenDeSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaDestino");

                    b.Navigation("OrdenDeSolicitud");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.OrdenDeSolicitud", b =>
                {
                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.CentroDeCosto", "CentroDeCosto")
                        .WithMany()
                        .HasForeignKey("IdCentroDeCosto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.EstadoDeSolicitud", "EstadoDeSolicitud")
                        .WithMany()
                        .HasForeignKey("IdEstadoDeSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.PrioridadDeOrden", "PrioridadDeOrden")
                        .WithMany()
                        .HasForeignKey("IdPriodidadDeOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.UsuarioSolicitante", "UsuarioSolicitante")
                        .WithMany()
                        .HasForeignKey("IdUsuarioSolicitante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroDeCosto");

                    b.Navigation("Empresa");

                    b.Navigation("EstadoDeSolicitud");

                    b.Navigation("PrioridadDeOrden");

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Producto", b =>
                {
                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.TipoDeUnidad", "TipoDeUnidad")
                        .WithMany()
                        .HasForeignKey("IdTipoDeUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDeUnidad");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.StockProducto", b =>
                {
                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("IdAlmacen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Empresa");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.UbicacionDestino", b =>
                {
                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenIdAlmacen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");
                });

            modelBuilder.Entity("SistemaIntegralReportes.AplicacionDePedidos.Entidades.UsuarioSolicitante", b =>
                {
                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralReportes.AplicacionDePedidos.Entidades.RolDeUsuario", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
