// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaIntegralReportes.EntityModels;

#nullable disable

namespace SistemaIntegralReportes.Migrations
{
    [DbContext(typeof(SistemaIntegralReportesContext))]
    [Migration("20230519143524_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaIntegralReportes.EntityModels.ConfAcceso", b =>
                {
                    b.Property<int>("IdAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_acceso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAcceso"), 1L, 1);

                    b.Property<int>("IdModulo")
                        .HasColumnType("int")
                        .HasColumnName("id_modulo");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int")
                        .HasColumnName("id_perfil");

                    b.Property<bool>("Permitido")
                        .HasColumnType("bit")
                        .HasColumnName("permitido");

                    b.HasKey("IdAcceso", "IdModulo", "IdPerfil");

                    b.HasIndex("IdModulo");

                    b.HasIndex("IdPerfil");

                    b.ToTable("conf_accesos", (string)null);
                });

            modelBuilder.Entity("SistemaIntegralReportes.EntityModels.ConfModulo", b =>
                {
                    b.Property<int>("IdModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_modulo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModulo"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("icono")
                        .IsFixedLength();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("nombre")
                        .IsFixedLength();

                    b.Property<string>("RouteLink")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("routeLink")
                        .IsFixedLength();

                    b.HasKey("IdModulo");

                    b.ToTable("conf_modulo", (string)null);
                });

            modelBuilder.Entity("SistemaIntegralReportes.EntityModels.ConfPerfile", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_perfil");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerfil"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("NombrePerfil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_perfil");

                    b.HasKey("IdPerfil");

                    b.ToTable("conf_perfiles", (string)null);
                });

            modelBuilder.Entity("SistemaIntegralReportes.EntityModels.ConfUsuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contrasenia");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int")
                        .HasColumnName("id_perfil");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPerfil");

                    b.ToTable("conf_usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaIntegralReportes.EntityModels.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("icono")
                        .IsFixedLength();

                    b.Property<int>("IdModulo")
                        .HasColumnType("int")
                        .HasColumnName("id_modulo");

                    b.Property<string>("NombreReporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("nombre_reporte")
                        .IsFixedLength();

                    b.Property<string>("RouteLink")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("routeLink")
                        .IsFixedLength();

                    b.HasKey("IdReporte")
                        .HasName("PK_dbo.reportes");

                    b.ToTable("reportes", (string)null);
                });

            modelBuilder.Entity("SistemaIntegralReportes.EntityModels.ConfAcceso", b =>
                {
                    b.HasOne("SistemaIntegralReportes.EntityModels.ConfModulo", "IdModuloNavigation")
                        .WithMany("ConfAccesos")
                        .HasForeignKey("IdModulo")
                        .IsRequired()
                        .HasConstraintName("FK_conf_accesos_conf_modulo");

                    b.HasOne("SistemaIntegralReportes.EntityModels.ConfPerfile", "IdPerfilNavigation")
                        .WithMany("ConfAccesos")
                        .HasForeignKey("IdPerfil")
                        .IsRequired()
                        .HasConstraintName("FK_conf_accesos_conf_perfiles");

                    b.Navigation("IdModuloNavigation");

                    b.Navigation("IdPerfilNavigation");
                });

            modelBuilder.Entity("SistemaIntegralReportes.EntityModels.ConfUsuario", b =>
                {
                    b.HasOne("SistemaIntegralReportes.EntityModels.ConfPerfile", "IdPerfilNavigation")
                        .WithMany("ConfUsuarios")
                        .HasForeignKey("IdPerfil")
                        .IsRequired()
                        .HasConstraintName("FK_conf_usuarios_conf_perfiles");

                    b.Navigation("IdPerfilNavigation");
                });

            modelBuilder.Entity("SistemaIntegralReportes.EntityModels.ConfModulo", b =>
                {
                    b.Navigation("ConfAccesos");
                });

            modelBuilder.Entity("SistemaIntegralReportes.EntityModels.ConfPerfile", b =>
                {
                    b.Navigation("ConfAccesos");

                    b.Navigation("ConfUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
