//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _52_ControlUsuariosDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class conf_accesos
    {
        [Key]
        public int id_acceso { get; set; }
        public int id_modulo { get; set; }
        public int id_perfil { get; set; }
        public bool permitido { get; set; }
    
        public virtual conf_modulo conf_modulo { get; set; }
        public virtual conf_perfiles conf_perfiles { get; set; }
    }
}
