//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _52_ControlUsuariosDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class conf_usuarios
    {
        [Key]
        public int id_usuario { get; set; }
        public int id_perfil { get; set; }
        public string nombre_usuario { get; set; }
        public string contrasenia { get; set; }
        public bool activo { get; set; }
        public string nombre_completo { get; set; }

        [ForeignKey("id_perfil")]
        public virtual conf_perfiles conf_perfiles { get; set; }
    }
}
