// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaIntegralReportes.Aplicacion.Android;

#nullable disable

namespace SistemaIntegralReportes.Aplicacion.Android.Migrations
{
    [DbContext(typeof(ApplicationDbContextAndroid))]
    [Migration("20241129111501_testDeTablas")]
    partial class testDeTablas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaIntegralReportes.Aplicacion.Android.Entidades.Incidente.Incidente", b =>
                {
                    b.Property<int>("IdIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncidente"), 1L, 1);

                    b.Property<string>("CodigoDeEmpleado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoDeProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdTipoDeIncidente")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImagenDeIncidente")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("NombreDeEmpleado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PuestoDeTrabajo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("codigoQr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdIncidente");

                    b.HasIndex("IdTipoDeIncidente");

                    b.ToTable("test_incidentes");
                });

            modelBuilder.Entity("SistemaIntegralReportes.Aplicacion.Android.Entidades.Incidente.SectorDeIncidente", b =>
                {
                    b.Property<int>("IdSectorIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSectorIncidente"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSectorIncidente");

                    b.ToTable("test_sector_de_incidente");
                });

            modelBuilder.Entity("SistemaIntegralReportes.Aplicacion.Android.Entidades.Incidente.TipoDeIncidente", b =>
                {
                    b.Property<int>("IdTipoDeIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDeIncidente"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdSectorDeIncidente")
                        .HasColumnType("int");

                    b.HasKey("IdTipoDeIncidente");

                    b.HasIndex("IdSectorDeIncidente");

                    b.ToTable("test_tipo_de_incidente");
                });

            modelBuilder.Entity("SistemaIntegralReportes.Aplicacion.Android.Entidades.Incidente.Incidente", b =>
                {
                    b.HasOne("SistemaIntegralReportes.Aplicacion.Android.Entidades.Incidente.TipoDeIncidente", "TipoDeIncidente")
                        .WithMany()
                        .HasForeignKey("IdTipoDeIncidente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDeIncidente");
                });

            modelBuilder.Entity("SistemaIntegralReportes.Aplicacion.Android.Entidades.Incidente.TipoDeIncidente", b =>
                {
                    b.HasOne("SistemaIntegralReportes.Aplicacion.Android.Entidades.Incidente.SectorDeIncidente", "SectorDeIncidente")
                        .WithMany()
                        .HasForeignKey("IdSectorDeIncidente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectorDeIncidente");
                });
#pragma warning restore 612, 618
        }
    }
}
